export enum ActionTypes {
  ACTION_LOGIN = 'ACTION_LOGIN',
  PRODUCTS_DATA_LIST = 'PRODUCTS_DATA_LIST',
  PRODUCTS_SEARCH = 'PRODUCTS_SEARCH',
  GLOBAL_CONNECTION = 'GLOBAL_CONNECTION',
  PRODUCTS_FILTER = 'PRODUCTS_FILTER',
  SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY',
  CATEGORIES_LIST = 'CATEGORIES_LIST'
}

export default ActionTypes;
