export enum ActionTypes {
  ACTION_LOGIN = 'ACTION_LOGIN',
  PRODUCTS_DATA_LIST = 'PRODUCTS_DATA_LIST',
  PRODUCTS_SEARCH = 'PRODUCTS_SEARCH',
  GLOBAL_CONNECTION = 'GLOBAL_CONNECTION',
  PRODUCTS_FILTER = 'PRODUCTS_FILTER',
  SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY',
  CATEGORIES_LOADING = 'CATEGORIES_LOADING',
  CATEGORIES_LIST = 'CATEGORIES_LIST',
  SET_FILTER_BRAND = 'SET_FILTER_BRAND',
  PRODUCTS_FILTER_CATEGORY = 'PRODUCTS_FILTER_CATEGORY',
  PRODUCTS_FILTER_BRANDS = 'PRODUCTS_FILTER_BRANDS',
  PRODUCTS_FILTER_PRICES = 'PRODUCTS_FILTER_PRICES',
  PRODUCT_FILTER_CHILD_CATEGORY = 'PRODUCT_FILTER_CHILD_CATEGORY',
  PRODUCT_FILTER_CHILD_BRAND = 'PRODUCT_FILTER_CHILD_BRAND',
  IS_LOADING = 'IS_LOADING',
  PRODUCTS_FILTER_PRICES_VALUE = 'PRODUCTS_FILTER_PRICES_VALUE'
}

export default ActionTypes;
